[package]
name = "wikidle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

parse_wiki_text = "0.1.5"
xml-rs = "0.8.4"
regex = "1.5.5"
lazy_static = "1.4.0"